name: build_uboot_for_GL-MT2500
on: 
  workflow_dispatch:
    inputs:
      fixed_mtdparts:
        description: 'Fixed mtd parts? (will not follow uboot env)'
        required: true
        type: boolean
        default: 'true'
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build for GL-MT2500 with fixed mtdparts

        run: |
          sudo apt update
          sudo apt install build-essential bison flex bc libssl-dev python-is-python3 device-tree-compiler gcc-aarch64-linux-gnu
          export CROSS_COMPILE=aarch64-linux-gnu-
          git clone https://github.com/66o99/bl-mt798x
          cd bl-mt798x
          SOC=gl BOARD=mt2500 ./build.sh               

      - name: Upload FIP file
        with: 
            name: GL-MT2500_uboot_fip
            path: bl-mt798x/atf-20220606-637ba581b/build/mt7981/release/fip.bin
